### ISSUE TITLE
trained model cannot be download,403 error

### ISSUE THREAD

**Issue by tsing-cv** [jacquelinelala/GFN#1]

**Comment by jacquelinelala** [comment]
Thanks for your attention. There is something wrong with my server, and I
zipped the model and uploaded it once again. You may try to download now.
The testing dataset is uploading, please follow my updates on my website(
xinyizhang.tech) and Github link(https://github.com/jacquelinelala/GFN).

On Aug 22, 2018, at 10:34, tsing-cv <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacquelinelala/GFN/issues/1>, or mute the thread
