### ISSUE TITLE
Question about the method

### ISSUE THREAD

**Issue by CVHW** [jacquelinelala/GFN#23]
Dear author, 
 
thanks for your public code. I have a question below:
Did you try to use the result of the deblurring branch as the input of the super-resolution branch instead of the original input? If you employ this strategy, you could achieve a better result? 

I am looking forward to your reply. Thank you.

**Comment by jacquelinelala** [comment]
Our ablation study shows that the concatenation of deblurring branch and SR branch(Model-1 on supplementary materials) is not as good as our dual-branch strategy due to the error accumulation. You can find the ablation study and more analysis on our paper and supplementary materials(http://xinyizhang.tech/files/supplement_bmvc2018.zip).

**Comment by CVHW** [comment]
Thanks for your reply.



发自我的iPhone


------------------ Original ------------------
